# Generated by Django 5.0.1 on 2024-01-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='completed',
        ),
    ]
